version: '3'
services:
  spark-master:
    build: .
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"  # Spark UI
      - "7077:7077"  # Spark master port
      - "6066:6066"  # Spark REST API
      - "4040:4040"  # Spark application UI
    volumes:
      - ./data:/data
      - ./scripts:/scripts
      - ./warehouse:/warehouse/iceberg  # Mount the Iceberg warehouse directory
    environment:
      - "SPARK_LOCAL_IP=spark-master"